pages:
  stage: deploy
  image: $CI_REGISTRY/ict/images/alpine/ci:latest
  script:
    - mkdir -p public/
    # .fit-pages.yml must be in public/
    - cp .fit-pages.yml public/
    # Do whatever you need to generate static content of your web, for example:
    - cp *.html public/
    - cp *.js public/
  artifacts:
    paths:
      - public/
    expire_in: 1 hour